/* PrivateFrameworks/UIAutomation.framework
 *
 * Copyright © 2012, Apple Inc. All rights reserved.
 *
 ******************************************************************************/

#import <Foundation/NSObject.h>

@class NSInvocation;

@interface UIAElementNil : NSObject<NSFastEnumeration>
{
	NSInvocation *_selfPatienceInvocation;
	double _refreshedTime;
	double _lastAccessedTime;
}

+ (int)_liveCount;
+ (int)_maxCount;
+ (id)_elementNilWithInvocation:(id)arg1;
- (id)_selfPatienceInvocation;
- (void)_setSelfPatienceInvocation:(id)arg1;
- (id)_objectWithPatienceInvocationFromUIAObject:(id)arg1 selector:(SEL)arg2;
- (id)_initWithInvocation:(id)arg1;
- (void)dealloc;
- (double)_refreshedTime;
- (double)_lastAccessedTime;
- (void)_setLastAccessedTime:(double)arg1;
- (BOOL)_isStillFreshAtTime:(double)arg1;
- (id)_elementNilWithPatienceInvocation:(SEL)arg1;
- (id)scriptingInvocationString;
- (id)scriptingInvocationFullExpressionString;
- (BOOL)isValid;
- (BOOL)checkIsValid;
- (BOOL)waitForInvalid;
- (id)withName:(id)arg1;
- (id)withValue:(id)arg1 forKey:(id)arg2;
- (id)withPredicate:(id)arg1;
- (unsigned int)count;
- (id)objectAtIndex:(unsigned int)arg1;
- (id)nsArray;
- (BOOL)containsObject:(id)arg1;
- (unsigned int)indexOfObject:(id)arg1;
- (id)objectEnumerator;
- (id)reverseObjectEnumerator;
- (unsigned int)countByEnumeratingWithState:(NSFastEnumerationState *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (id)firstWithName:(id)arg1;
- (id)firstWithValue:(id)arg1 forKey:(id)arg2;
- (id)firstWithPredicate:(id)arg1;
- (id)elementOfClass:(Class)arg1 atIndex:(unsigned int)arg2;
- (void)_raiseInvalidElementAction;
- (void)tap;
- (void)doubleTap;
- (void)twoFingerTap;
- (void)tapWithOptions:(id)arg1;
- (void)touchAndHold:(id)arg1;
- (void)choose;
- (void)dragToValue:(id)arg1;
- (void)selectValue:(id)arg1;
- (void)dismiss;
- (void)goToNextPage;
- (void)goToPreviousPage;
- (void)selectPage:(id)arg1;
- (void)dragInsideWithOptions:(id)arg1;
- (void)flickInsideWithOptions:(id)arg1;
- (void)rotateWithOptions:(id)arg1;
- (void)activate;
- (void)scrollUp;
- (void)scrollDown;
- (void)scrollLeft;
- (void)scrollRight;
- (void)scrollToVisible;
- (id)scrollToElementWithName:(id)arg1;
- (id)scrollToElementWithPredicate:(id)arg1;
- (id)scrollToElementWithValue:(id)arg1 forKey:(id)arg2;
- (UIAElementArray *)elements;
- (UIAElementArray *)activityIndicators;
- (UIAElementArray *)buttons;
- (UIAElementArray *)editingMenus;
- (UIAElementArray *)images;
- (UIAElementArray *)keyboards;
- (UIAElementArray *)keys;
- (UIAElementArray *)links;
- (UIAElementArray *)pageIndicators;
- (UIAElementArray *)pickers;
- (id)popover;
- (UIAElementArray *)progressIndicators;
- (UIAElementArray *)scrollViews;
- (UIAElementArray *)segmentedControls;
- (UIAElementArray *)staticTexts;
- (UIAElementArray *)switches;
- (UIAElementArray *)sliders;
- (UIAElementArray *)textFields;
- (UIAElementArray *)secureTextFields;
- (UIAElementArray *)tableViews;
- (UIAElementArray *)searchBars;
- (UIAElementArray *)textViews;
- (UIAElementArray *)webViews;
- (id)parentElement;
- (id)ancestry;
- (UIAElementArray *)windows;
- (id)keyWindow;
- (id)mainWindow;
- (UIAElementArray *)actionSheets;
- (id)actionSheet;
- (id)alert;
- (id)editingMenu;
- (id)switcherScrollView;
- (id)keyboard;
- (id)statusBar;
- (UIAElementArray *)navigationBars;
- (id)navigationBar;
- (UIAElementArray *)tabBars;
- (id)tabBar;
- (UIAElementArray *)toolbars;
- (id)toolbar;
- (id)leftButton;
- (id)rightButton;
- (id)selectedButton;
- (UIAElementArray *)wheels;
- (UIAElementArray *)headers;
- (UIAElementArray *)cells;
- (UIAElementArray *)visibleCells;
- (UIAElementArray *)groups;
- (UIAElementArray *)visibleGroups;
- (id)rect;
- (id)hitpoint;
- (id)name;
- (id)label;
- (id)hint;
- (id)value;
- (id)url;
- (id)dom;
- (void)setValue:(id)arg1;
- (id)pid;
- (id)helpTag;
- (id)isEnabled;
- (id)isVisible;
- (id)isCameraIrisOpen;
- (id)hasKeyboardFocus;
- (id)hasOpenMenu;
- (id)target;
- (id)depth;
- (id)visibleFrame;
- (id)bundlePath;
- (id)version;
- (id)bundleID;
- (id)bundleVersion;
- (id)localizedStringForKey:(id)arg1 value:(id)arg2 table:(id)arg3;
- (UIAElementArray *)localizations;
- (id)stateDescription;
- (id)architecture;
- (id)isFront;
- (id)isBackgroundApp;
- (id)cancelButton;
- (id)defaultButton;
- (id)isSeparatorItem;
- (id)keyEquivalent;
- (UIAElementArray *)keyEquivalentModifiers;
- (id)contentArea;
- (id)orientation;
- (id)minValue;
- (id)maxValue;
- (id)textLength;
- (id)numberOfCells;
- (UIAElementArray *)values;
- (id)selectedValue;
- (id)pageCount;
- (id)pageIndex;
- (id)_logInfoWithChildren;
- (void)logElement;
- (void)logElementTree;
- (void)logAXInfo;
- (void)logAXTree;

@end
